export const lineImg = [
  require('./LineImg1.jpg'),
  require('./LineImg2.jpg'),
]

export const headerImg = [
  require("./MainImg.jpg"),
  require("./List2HeaderImg.jpg"),
  require("./List3HeaderImg.jpg"),
  require("./List4HeaderImg.jpg"),
  require("./List5HeaderImg.jpg"),
  require("./List6HeaderImg.jpg"),
  require("./List7HeaderImg.jpg"),
]

export const article1 = [
  require("./List1Img1.jpg"),
  require("./List1Img2.jpg"),
  require("./List1Img3.jpg"),
  require("./List1Img4.jpg"),
  require("./List1Img5.jpg"),
  require("./List1Img6.jpg"),
]

export const article1Footer = require("./List1FooterImg.jpg");

export const article2 = [
  {
    img: require("./List2Img1.jpg"),
		name: "日常元素魔术无痕胶带",
    desc: "魔力吸附，来去无痕",
    price: "¥12.9",
    beforePrice: "",
  }, {
    img: require("./List2Img2.jpg"),
		name: "垃圾袋",
    desc: "让清洁更简单",
    price: "¥9.9",
    beforePrice: "¥14.9",
  }, {
    img: require("./List2Img3.jpg"),
		name: "MIJOY 纯棉洗脸巾",
    desc: "升级你的理想生活",
    price: "¥12.9",
    beforePrice: "",
  }, {
    img: require("./List2Img4.jpg"),
		name: "一往无前",
    desc: "雷军亲述小米热血10年",
    price: "¥58",
    beforePrice: "¥78",
  }, {
    img: require("./List2Img5.jpg"),
		name: "一次性医用口罩",
    desc: "轻身而行，畅然呼吸",
    price: "¥19",
    beforePrice: "",
  }, {
    img: require("./List2Img6.jpg"),
		name: "米家驱蚊器 智能版（3个装）",
    desc: "手机定时开关机，智能驱蚊更省心",
    price: "¥149",
    beforePrice: "",
  }, {
    img: require("./List2Img7.jpg"),
		name: "支架式自拍杆",
    desc: "解放双手，定格更美的镜头",
    price: "¥89",
    beforePrice: "",
  }, {
    img: require("./List2Img8.jpg"),
		name: "小米简约休闲双肩包",
    desc: "这一次，“轻”装上阵",
    price: "¥99",
    beforePrice: "",
  }, {
    img: require("./List2Img9.jpg"),
		name: "小米米家液晶小黑板",
    desc: "随想随画，记录灵感瞬间",
    price: "¥49",
    beforePrice: "",
  }, {
    img: require("./List2Img10.jpg"),
		name: "小米小背包",
    desc: "城市休闲，简约设计",
    price: "¥24.9",
    beforePrice: "",
  }, {
    img: require("./List2Img11.jpg"),
		name: "中性笔10支装",
    desc: "一支顶4支，超长顺滑书写",
    price: "¥9.99",
    beforePrice: "",
  }, {
    img: require("./List2Img12.jpg"),
		name: "日常元素抽纸",
    desc: "精选原生竹浆，健康环保",
    price: "¥27.9",
    beforePrice: "¥32.9",
  }, {
    img: require("./List2Img13.jpg"),
		name: "5号电池",
    desc: "无汞无镉 安全环保",
    price: "¥9.9",
    beforePrice: "",
  }, {
    img: require("./List2Img14.jpg"),
		name: "米家超级电池4粒装",
    desc: "稳定耐用",
    price: "¥19.9",
    beforePrice: "",
  }, {
    img: require("./List2Img15.jpg"),
		name: "小米GaN充电器 65W",
    desc: "氮化镓黑科技 65W MAX 大功率快充",
    price: "¥149",
    beforePrice: "",
  }, {
    img: require("./List2Img16.jpg"),
		name: "驱蚊片",
    desc: "长效驱蚊，蜂巢式设计",
    price: "¥29",
    beforePrice: "",
  }, {
    img: require("./List2Img17.jpg"),
		name: "小魔爪按摩器",
    desc: "全身按摩，小巧百搭",
    price: "¥9.9",
    beforePrice: "",
  }, {
    img: require("./List2Img18.jpg"),
		name: "小米多功能运动休闲胸包",
    desc: "小而精致，精简出行",
    price: "¥69",
    beforePrice: "",
  }, {
    img: require("./List2Img19.jpg"),
		name: "MIJOY粘毛器",
    desc: "收纳手柄，小巧便携",
    price: "¥14.9",
    beforePrice: "",
  }, {
    img: require("./List2Img20.jpg"),
		name: "MIJOY 香薰",
    desc: "复古唱片造型",
    price: "¥49",
    beforePrice: "",
  }, {
    img: require("./List2Img21.jpg"),
		name: "抽纸（标准版）",
    desc: "一张抽纸，给你舒适与洁净",
    price: "¥39.9",
    beforePrice: "¥49",
  }, {
    img: require("./List2Img22.jpg"),
		name: "中性笔10支装",
    desc: "一支顶4支，超长顺滑书写",
    price: "¥9.99",
    beforePrice: "",
  }, {
    img: require("./List2Img23.jpg"),
		name: "米家蓝牙温湿度计 2",
    desc: "冷暖干湿,一望而知",
    price: "¥29",
    beforePrice: "",
  }, {
    img: require("./List2Img24.jpg"),
		name: "Redmi充电宝",
    desc: "双输入接口，双输出接口",
    price: "¥59",
    beforePrice: "",
  }, {
    img: require("./List2Img25.jpg"),
		name: "小米休闲运动双肩包",
    desc: "让你的出行更轻松",
    price: "¥149",
    beforePrice: "",
  }, {
    img: require("./List2Img26.jpg"),
		name: "小米移动电源3 20000mAh USB-C双向快充版",
    desc: "双向快充，双口输入，智能兼容更聪明",
    price: "¥129",
    beforePrice: "",
  }, {
    img: require("./List2Img27.jpg"),
		name: "最生活毛巾",
    desc: "给生活一条好毛巾",
    price: "¥99",
    beforePrice: "¥169",
  }, {
    img: require("./List2Img28.jpg"),
		name: "MIJOY 临时停车牌",
    desc: "您的停车小助手",
    price: "¥16.9",
    beforePrice: "",
  }, {
    img: require("./List2Img29.jpg"),
		name: "MIJOY水槽过滤网 100只装",
    desc: "水槽清理，只需一提",
    price: "¥9.9",
    beforePrice: "",
  }, {
    img: require("./List2Img30.jpg"),
		name: "智能睡眠牵引枕",
    desc: "深度牵引，改善颈椎曲线；促睡眠",
    price: "¥309",
    beforePrice: "¥359",
  }, {
    img: require("./List2Img31.jpg"),
		name: "米家魔方转换器",
    desc: "方寸之间，能量无限",
    price: "¥59",
    beforePrice: "",
  }, {
    img: require("./List2Img32.jpg"),
		name: "MIJOY一次性套装（浴巾+毛巾）",
    desc: "开启美好旅行新体验",
    price: "¥9.9",
    beforePrice: "",
  }, {
    img: require("./List2Img33.jpg"),
		name: "清洁湿巾",
    desc: "纯水洁肤 洁净安心",
    price: "¥9.99",
    beforePrice: "",
  }, {
    img: require("./List2Img34.jpg"),
		name: "乐范记忆绵护颈U型枕",
    desc: "周全呵护你的颈椎",
    price: "¥49",
    beforePrice: "",
  }, {
    img: require("./List2Img35.jpg"),
		name: "小米金属旅行箱 2",
    desc: "精湛工艺，体面出行",
    price: "¥999",
    beforePrice: "",
  }, {
    img: require("./List2Img36.jpg"),
		name: "小米记录仪2 2K版",
    desc: "超清画质",
    price: "¥399",
    beforePrice: "",
  }, {
    img: require("./List2Img37.jpg"),
		name: "小米无线键鼠套装",
    desc: "轻松畅享，无线办公",
    price: "¥89",
    beforePrice: "",
  }, {
    img: require("./List2Img38.jpg"),
		name: "小米无线鼠标",
    desc: "简约设计，轻盈握感",
    price: "¥29",
    beforePrice: "¥39",
  }, {
    img: require("./List2Img39.jpg"),
		name: "支架式自拍杆",
    desc: "解放双手，定格更美的镜头",
    price: "¥89",
    beforePrice: "",
  }, 
]

export const article3 = [
  {
    img: require("./List3Img1.jpg"),
		name: "小米旅行箱 青春款 系列",
    desc: "环保材料，轻便重量",
    price: "¥199",
    beforePrice: "",
  }, {
    img: require("./List3Img2.jpg"),
		name: "小米极简都市双肩包 2",
    desc: "简约挺括，彰显年轻活力",
    price: "¥149",
    beforePrice: "",
  }, {
    img: require("./List3Img3.jpg"),
		name: "米家运动鞋4",
    desc: "轻盈若絮,弹若脱兔",
    price: "¥179",
    beforePrice: "",
  }, {
    img: require("./List3Img4.jpg"),
		name: "米家精修螺丝刀套装",
    desc: "精致极简，满足大多数日常需求",
    price: "¥99",
    beforePrice: "",
  }, {
    img: require("./List3Img5.jpg"),
		name: "米家手自一体电动螺丝刀",
    desc: "小巧有力，得心应手",
    price: "¥149",
    beforePrice: "",
  }, {
    img: require("./List3Img6.jpg"),
		name: "米家电动螺丝刀",
    desc: "专利一体化无绳设计，轻松开工",
    price: "¥199",
    beforePrice: "",
  }, {
    img: require("./List3Img7.jpg"),
		name: "小米体脂秤2",
    desc: "轻松掌握身体脂肪率",
    price: "¥99",
    beforePrice: "",
  }, {
    img: require("./List3Img8.jpg"),
		name: "米家泡沫洁面机",
    desc: "泡泡洗脸，深度净爽",
    price: "¥99",
    beforePrice: "",
  }, {
    img: require("./List3Img9.jpg"),
		name: "米家负离子便携吹风机H100",
    desc: "柔顺护发，折叠好收纳",
    price: "¥99",
    beforePrice: "",
  }, {
    img: require("./List3Img10.jpg"),
		name: "米家声波电动牙刷T100 白色",
    desc: "专业高频震动，更清洁的刷牙方式",
    price: "¥39.9",
    beforePrice: "",
  }, {
    img: require("./List3Img11.jpg"),
		name: "米家防飞溅指甲刀",
    desc: "锋利耐用，防飞溅收纳套壳设计",
    price: "¥9.9",
    beforePrice: "",
  }, {
    img: require("./List3Img12.jpg"),
		name: "米家电动剃须刀S500",
    desc: "浮动贴面更干净，减压设计更舒适",
    price: "¥199",
    beforePrice: "",
  }, {
    img: require("./List3Img13.jpg"),
		name: "MIJOY一次性套装（浴巾+毛巾）",
    desc: "开启美好旅行新体验",
    price: "¥9.9",
    beforePrice: "",
  }, {
    img: require("./List3Img14.jpg"),
		name: "迷你保温杯",
    desc: "可以随身携带的温度",
    price: "¥49",
    beforePrice: "",
  }, {
    img: require("./List3Img15.jpg"),
		name: "支架式自拍杆",
    desc: "解放双手，定格更美的镜头",
    price: "¥89",
    beforePrice: "",
  }, {
    img: require("./List3Img16.jpg"),
		name: "防蓝光护目镜",
    desc: "轻盈舒适，护眼新体验",
    price: "¥99",
    beforePrice: "",
  }, {
    img: require("./List3Img17.jpg"),
		name: "飞行员太阳镜",
    desc: "偏光镜片，结构升级",
    price: "¥99",
    beforePrice: "",
  }, {
    img: require("./List3Img18.jpg"),
		name: "方框太阳镜",
    desc: "复古设计，偏光自修复",
    price: "¥99",
    beforePrice: "",
  },
]

export const article4 = [
  {
    img: require("./List4Img1.jpg"),
		name: "多功能双肩包 2",
    desc: "商务旅行多场景，切换无压力",
    price: "¥199",
    beforePrice: "",
  }, {
    img: require("./List4Img2.jpg"),
		name: "商务双肩包 2",
    desc: "实用商务时尚范 经典设计 空间利用率高",
    price: "¥99",
    beforePrice: "",
  }, {
    img: require("./List4Img3.jpg"),
		name: "小米休闲运动双肩包",
    desc: "让你的出行更轻松",
    price: "¥149",
    beforePrice: "",
  }, {
    img: require("./List4Img4.jpg"),
		name: "小米小背包",
    desc: "城市休闲，简约设计",
    price: "¥24.9",
    beforePrice: "",
  }, {
    img: require("./List4Img5.jpg"),
		name: "休闲胸包",
    desc: "装下你出行的所有需求",
    price: "¥59",
    beforePrice: "",
  }, {
    img: require("./List4Img6.jpg"),
		name: "小米简约休闲双肩包",
    desc: "这一次，“轻”装上阵",
    price: "¥69",
    beforePrice: "",
  }, {
    img: require("./List4Img7.jpg"),
		name: "小米多功能运动休闲胸包",
    desc: "小而精致，精简出行",
    price: "¥69",
    beforePrice: "",
  }, {
    img: require("./List4Img8.jpg"),
		name: "90分框体旅行箱系列",
    desc: "专利轻量合金中框，轻盈坚固 ",
    price: "¥399",
    beforePrice: "",
  }, {
    img: require("./List4Img9.jpg"),
		name: "米家运动鞋4",
    desc: "轻盈若絮,弹若脱兔",
    price: "¥179",
    beforePrice: "",
  }, {
    img: require("./List4Img10.jpg"),
		name: "平衡车",
    desc: "年轻人的酷玩具",
    price: "¥1999",
    beforePrice: "",
  }, {
    img: require("./List4Img11.jpg"),
		name: "电动滑板车1S",
    desc: "型出格，行出色",
    price: "¥1999",
    beforePrice: "",
  }, {
    img: require("./List4Img12.jpg"),
		name: "骑记电动助力自行车",
    desc: "更多助力选择，更多城市风景",
    price: "¥2999",
    beforePrice: "",
  },
]

export const article5 = [
  {
    img: require("./List5Img1.jpg"),
		name: "扫拖一体机器人",
    desc: "扫得干净，拖得彻底",
    price: "¥1799",
    beforePrice: "¥1999",
  }, {
    img: require("./List5Img2.jpg"),
		name: "小米「小爱老师」",
    desc: "英语提分利器",
    price: "¥499",
    beforePrice: "",
  }, {
    img: require("./List5Img3.jpg"),
		name: "智能门锁",
    desc: "一体化活体指纹识别",
    price: "¥1299",
    beforePrice: "",
  }, {
    img: require("./List5Img4.jpg"),
		name: "米家天然乳胶护颈枕S",
    desc: "大颗粒释压体验，升级好睡眠",
    price: "¥199",
    beforePrice: "",
  }, {
    img: require("./List5Img5.jpg"),
		name: "8H记忆绵护椎腰靠",
    desc: "处处体贴，为你撑腰",
    price: "¥89",
    beforePrice: "",
  }, {
    img: require("./List5Img6.jpg"),
		name: "米家护颈记忆绵枕",
    desc: "高低曲线承托，睡眠更自在",
    price: "¥99",
    beforePrice: "",
  }, {
    img: require("./List5Img7.jpg"),
		name: "小米体脂秤2",
    desc: "轻松掌握身体脂肪率",
    price: "¥99",
    beforePrice: "",
  }, {
    img: require("./List5Img8.jpg"),
		name: "自动泡沫洗洁精机套装",
    desc: "感应出泡，高效清洁",
    price: "¥59",
    beforePrice: "",
  }, {
    img: require("./List5Img9.jpg"),
		name: "米家自动洗手机套装",
    desc: "伸手出泡，抑菌有效",
    price: "¥79",
    beforePrice: "",
  }, {
    img: require("./List5Img10.jpg"),
		name: "最生活毛巾",
    desc: "给生活一条好毛巾",
    price: "¥99",
    beforePrice: "¥169",
  }, {
    img: require("./List5Img11.jpg"),
		name: "浴巾Air 4条装",
    desc: "享用一条洁净好浴巾",
    price: "¥169",
    beforePrice: "",
  }, {
    img: require("./List5Img12.jpg"),
		name: "最生活毛巾",
    desc: "3秒吸水，杀菌无刺激",
    price: "¥19.9",
    beforePrice: "",
  },
]

export const article6 = [
  {
    img: require("./List6Img1.jpg"),
		name: "飞行员太阳镜",
    desc: "偏光镜片，结构升级",
    price: "¥99",
    beforePrice: "",
  }, {
    img: require("./List6Img2.jpg"),
		name: "防蓝光护目镜",
    desc: "轻盈舒适，护眼新体验",
    price: "¥99",
    beforePrice: "",
  }, {
    img: require("./List6Img3.jpg"),
		name: "方框太阳镜",
    desc: "复古设计，偏光自修复",
    price: "¥99",
    beforePrice: "",
  }, {
    img: require("./List6Img4.jpg"),
		name: "米家飞行员太阳镜 Pro",
    desc: "尼龙偏光，轻巧佩戴",
    price: "¥199",
    beforePrice: "",
  }, {
    img: require("./List6Img5.jpg"),
		name: "护目镜 Pro",
    desc: "科学护眼 舒适防污",
    price: "¥149",
    beforePrice: "",
  }, {
    img: require("./List6Img6.jpg"),
		name: "米家运动鞋4",
    desc: "轻盈若絮,弹若脱兔",
    price: "¥179",
    beforePrice: "¥199",
  }, 
]

export const article7 = [
  {
    img: require("./List7Img1.jpg"),
		name: "烟灶套装 天然气",
    desc: "点火排烟，风随火动",
    price: "¥2298",
    beforePrice: "",
  }, {
    img: require("./List7Img2.jpg"),
		name: "米家互联网吸油烟机",
    desc: "颜值过人的大吸力油烟机",
    price: "¥1499",
    beforePrice: "",
  }, {
    img: require("./List7Img3.jpg"),
		name: "平衡车燃动版",
    desc: "燃动升级，随走随停",
    price: "¥2299",
    beforePrice: "",
  }, {
    img: require("./List7Img4.jpg"),
		name: "小米智能多模网关",
    desc: "智能家庭控制中心",
    price: "¥129",
    beforePrice: "",
  }, {
    img: require("./List7Img5.jpg"),
		name: "小米光照传感器",
    desc: "精准感知光照变化",
    price: "¥49",
    beforePrice: "",
  }, {
    img: require("./List7Img6.jpg"),
		name: "米家智能插座蓝牙网关版",
    desc: "让传统家电变智能",
    price: "¥79",
    beforePrice: "",
  }, {
    img: require("./List7Img7.jpg"),
		name: "电子温湿度计Pro",
    desc: "知冷暖懂干湿的电子表",
    price: "¥49",
    beforePrice: "",
  }, {
    img: require("./List7Img8.jpg"),
    name: "智能礼品装",
    desc: "实时感应门窗开关状态",
    price: "¥329",
    beforePrice: "",
  }, {
    img: require("./List7Img9.jpg"),
		name: "小米米家智能插座WiFi版",
    desc: "让普通电器变智能",
    price: "¥49",
    beforePrice: "",
  }, {
    img: require("./List7Img10.jpg"),
		name: "小米插线板",
    desc: "3个USB充电口，支持快充",
    price: "¥49",
    beforePrice: "",
  }, {
    img: require("./List7Img11.jpg"),
		name: "插线板6位",
    desc: "小巧设计，便捷不占地儿",
    price: "¥79",

    beforePrice: "",
  }, {
    img: require("./List7Img12.jpg"),
    name: "四位四控插线板",
    desc: "四位分控，随用随开",
    price: "¥89",
    beforePrice: "",
  }, {
    img: require("./List7Img13.jpg"),
		name: "MIJOY 临时停车牌",
    desc: "您的停车小助手",
    price: "¥16.9",
    beforePrice: "",
  }, {
    img: require("./List7Img14.jpg"),
		name: "清洁湿巾",
    desc: "纯水洁肤 洁净安心",
    price: "¥9.99",
    beforePrice: "",
  }, {
    img: require("./List7Img15.jpg"),
		name: "插线板 5孔位",
    desc: "多重安全保护",
    price: "¥39",
    beforePrice: "",
  }, {
    img: require("./List7Img16.jpg"),
		name: "小米对讲机1S",
    desc: "再次出发，陪你轻聊一路",
    price: "¥249",
    beforePrice: "",
  }, {
    img: require("./List7Img17.jpg"),
		name: "米家魔方转换器",
    desc: "方寸之间，能量无限",
    price: "¥59",
    beforePrice: "",
  }, {
    img: require("./List7Img18.jpg"),
		name: "米家天然乳胶护颈枕S",
    desc: "大颗粒释压体验，升级好睡眠",
    price: "¥199",
    beforePrice: "",
  }, {
    img: require("./List7Img19.jpg"),
		name: "米家二位二控转换器",
    desc: "插孔一转二，实用不凌乱",
    price: "¥29.9",
    beforePrice: "",
  }, {
    img: require("./List7Img20.jpg"),
		name: "3位插线板",
    desc: "极简设计，轻松便捷",
    price: "¥29.9",
    beforePrice: "",
  }, {
    img: require("./List7Img21.jpg"),
		name: "吹风机架",
    desc: "吹风机必备伴侣",
    price: "¥29.9",
    beforePrice: "",
  }, {
    img: require("./List7Img22.jpg"),
		name: "米家驱蚊器 智能版（3个装）",
    desc: "手机定时开关机，智能驱蚊更省心",
    price: "¥149",
    beforePrice: "",
  }, {
    img: require("./List7Img23.jpg"),
		name: "日常元素抽纸",
    desc: "精选原生竹浆，健康环保",
    price: "¥27.9",
    beforePrice: "",
  }, {
    img: require("./List7Img24.jpg"),
		name: "迷你保温杯",
    desc: "可以随身携带的温度",
    price: "¥49",
    beforePrice: "",
  }, 
]